export const HUISHE_WINDOW_TYPE_DATA_FETCH = 'HUISHE_WINDOW_TYPE_DATA_FETCH'
export const HUISHE_WINDOW_TYPE_UPDATE = 'HUISHE_WINDOW_TYPE_UPDATE'
export const HUISHE_WINDOW_TYPE_CLONE_WIDGET = 'HUISHE_WINDOW_TYPE_CLONE_WIDGET'
export const HUISHE_WINDOW_TYPE_SET_CLONE_WIDGET_ID = 'HUISHE_WINDOW_TYPE_SET_CLONE_WIDGET_ID'

export const HUISHE_WINDOW_TYPE_WIDGET_ADD = 'HUISHE_WINDOW_TYPE_WIDGET_ADD'
export const HUISHE_WINDOW_TYPE_WIDGET_DESTROY = 'HUISHE_WINDOW_TYPE_WIDGET_DESTROY'
export const HUISHE_WINDOW_TYPE_WIDGET_UPDATE = 'HUISHE_WINDOW_TYPE_WIDGET_UPDATE'
export const HUISHE_WINDOW_TYPE_WIDGETS_UPDATE = 'HUISHE_WINDOW_TYPE_WIDGETS_UPDATE'
export const HUISHE_WINDOW_TYPE_UPDATE_WIDGET_BUUID = 'HUISHE_WINDOW_TYPE_UPDATE_WIDGET_BUUID'

export const WIDGET_CHART_OPTION_UPDATE = 'WIDGET_CHART_OPTION_UPDATE'
export const WIDGET_CHART_SETTING_UPDATE = 'WIDGET_CHART_SETTING_UPDATE'
export const WIDGET_CHART_STYLE_SETTING_UPDATE = 'WIDGET_CHART_STYLE_SETTING_UPDATE'

export const RENDER_CHART = 'RENDER_CHART'

export const HUISHE_WINDOW_TYPE_WIDGETS_DESTROY = 'HUISHE_WINDOW_TYPE_WIDGETS_DESTROY'

export const HUISHE_WINDOW_TYPE_EDGES_UPDATE = 'HUISHE_WINDOW_TYPE_EDGES_UPDATE'
