// 创建数据源
export const HUISHE_DATA_SOURCE_TYPE__CREATE = 'HUISHE_DATA_SOURCE_TYPE__CREATE'

// 获取数据源+数据集
export const HUISHE_DATA_SOURCE_TYPE_GET = 'HUISHE_DATA_SOURCE_TYPE_GET'

// 获取单个数据源
export const HUISHE_DATA_SOURCE_TYPE__GET = 'HUISHE_DATA_SOURCE_TYPE__GET'

// 清空单个数据源表单
export const HUISHE_DATA_SOURCE_TYPE__NULL = 'HUISHE_DATA_SOURCE_TYPE__NULL'

// 删除数据源
export const HUISHE_DATA_SOURCE_TYPE__DELETE = 'HUISHE_DATA_SOURCE_TYPE__DELETE'

// 修改数据源
export const HUISHE_DATA_SOURCE_TYPE__CHANGE = 'HUISHE_DATA_SOURCE_TYPE__CHANGE'

// 获取数据源
export const FETCH_HUISHE_DATA_SOURCE_TYPE_S = 'FETCH_HUISHE_DATA_SOURCE_TYPE_S'

// 测试数据源
export const HUISHE_DATA_SOURCE_TYPE__TEST = 'HUISHE_DATA_SOURCE_TYPE__TEST'
