// 新建-测试数据集
export const HUISHE_DATA_SET_TYPE_TEST = 'HUISHE_DATA_SET_TYPE_TEST'

// 新建-测试连接后获取字段
export const HUISHE_DATA_SET_TYPE_GET_FIELD = 'HUISHE_DATA_SET_TYPE_GET_FIELD'

// 新建-获取字段后下一步获取table数据
export const HUISHE_DATA_SET_TYPE_GET_TABLE = 'HUISHE_DATA_SET_TYPE_GET_TABLE'

// 新建-保存
export const HUISHE_DATA_SET_TYPE_SAVE = 'HUISHE_DATA_SET_TYPE_SAVE'

// 获取数据集信息
export const HUISHE_DATA_SET_TYPE_GET = 'HUISHE_DATA_SET_TYPE_GET'

// 删除数据集信息
export const HUISHE_DATA_SET_TYPE_NULL = 'HUISHE_DATA_SET_TYPE_NULL'

// 删除数据集
export const HUISHE_DATA_SET_TYPE_DELETE = 'HUISHE_DATA_SET_TYPE_DELETE'

// 获取数据集列表
export const HUISHE_DATA_SET_TYPE_LIST = 'HUISHE_DATA_SET_TYPE_LIST'

// 编辑-测试数据集
export const HUISHE_DATA_SET_TYPE_TEST_EDIT = 'HUISHE_DATA_SET_TYPE_TEST_EDIT'

// 编辑-测试连接后获取字段
export const HUISHE_DATA_SET_TYPE_GET_FIELD_EDIT = 'HUISHE_DATA_SET_TYPE_GET_FIELD_EDIT'

// 编辑-获取字段后下一步获取table数据
export const HUISHE_DATA_SET_TYPE_GET_TABLE_EDIT = 'HUISHE_DATA_SET_TYPE_GET_TABLE_EDIT'

// 编辑-保存
export const HUISHE_DATA_SET_TYPE_SAVE_EDIT = 'HUISHE_DATA_SET_TYPE_SAVE_EDIT'

// 编辑OpenAPI-保存
export const HUISHE_DATA_SET_TYPE_SAVE_OPENAPI = 'HUISHE_DATA_SET_TYPE_SAVE_OPENAPI'

export const HUISHE_DATA_SET_TYPE_DATA_LIST_FETCH = 'HUISHE_DATA_SET_TYPE_DATA_LIST_FETCH'

// 新建数据集时第一步保存用户输入
// export const SAVE_USER_INPUT = 'SAVE_USER_INPUT'


