export const HUISHE_WIDGET_TYPE_ADD = 'HUISHE_WIDGET_TYPE_ADD'
export const HUISHE_WIDGET_TYPE_UPDATE = 'HUISHE_WIDGET_TYPE_UPDATE'
export const HUISHE_WIDGET_TYPE_CREATE = 'HUISHE_WIDGET_TYPE_CREATE'
export const HUISHE_WIDGET_TYPE_DESTROY = 'HUISHE_WIDGET_TYPE_DESTROY'
