export const HUISHE_OPTIONS_TYPE_DATA_FETCH = 'HUISHE_OPTIONS_TYPE_DATA_FETCH'

export const  HUISHE_OPTIONS_TYPE_UPDATE = 'HUISHE_OPTIONS_TYPE_UPDATE'

// 数据源类型
export const  HUISHE_OPTIONS_TYPE_DATASOURCE = 'HUISHE_OPTIONS_TYPE_DATASOURCE'

// 数据类型
export const  HUISHE_OPTIONS_TYPE_DATATYPE = 'HUISHE_OPTIONS_TYPE_DATATYPE'

// 刷新周期
export const  HUISHE_OPTIONS_TYPE_REFRESH = 'HUISHE_OPTIONS_TYPE_REFRESH'

// 最近时间
export const  HUISHE_OPTIONS_TYPE_RECENT = 'HUISHE_OPTIONS_TYPE_RECENT'
